# Docker file for dbt and athena
FROM python:3.13

# Install dbt and dbt-athena
RUN pip install dbt dbt-athena

# Set the working directory
WORKDIR /dbt

# Copy the dbt profile
# COPY profiles.yml /root/.dbt/profiles.yml
