version: '3.8'

services:
  dbt-athena:
    build: .
    container_name: dbt-athena
    hostname: dbt-athena
    env_file:
      - .dbt-athena.env
    # Example variables for .dbt-athena.env
    # AWS_ACCESS_KEY_ID=your_access_key_id
    # AWS_SECRET_ACCESS_KEY=your_secret_access_key
    # AWS_REGION=your_region
    # DBT_PROFILES_DIR=/dbt
    # DBT_PROFILE_DIR=/dbt/profiles.yml

# Build command
# docker-compose up --build

# Run in background command
# docker-compose up -d

# NOTE: docker compose (for MacOS) or docker-compose (for Windows/Linux)